language: java
sudo: false
install: true

jdk: oraclejdk8

plugins: id "org.sonarqube" version "2.7"

sonarqube:
  properties:
    sonar.projectKey: caay2000_friend-challenge

addons:
  sonarcloud:
    organization: "caay2000-github"
    token:
      secure: "${token}"

script:
  - ./gradlew sonarqube